"""Sky-degeneracy folding for MBH flow proposals (offline harness prototype).

The LISA sky-mode group G (|G| = 8) is generated by SkyMove's two maps
(lisatools/sampling/moves/skymodehop.py), both EXACT isometries of the MBH
sampling basis:
  lat  : sin_beta -> -sin_beta, cos_iota -> -cos_iota, psi -> pi - psi
  long : lam -> lam + k*pi/2,   psi -> psi + k*pi/2 (mod pi),  k in {0,1,2,3}

Instead of asking a clustering to *discover* the resulting islands from thin
data (the ModeMixtureFlow route: measured to fail on 4-7-image leaves), we fold
them away analytically:

  train : fit ONE flow on rows canonicalised to the orbit image nearest a
          per-leaf reference -> a single island carrying ALL the leaf's rows.
  propose: u ~ q_u ; g ~ Uniform(G) ; x = g(u)
  density: q_x(x) = (1/8) sum_{g in G} q_u(g^-1 x)      [G-invariant, exact]

The density is the G-symmetrisation of q_u, so it is exact regardless of where
the trained flow puts its support (no reliance on the fold cut, no leakage
assumption). Jacobians are 1 (isometries). Cross-image jumps happen at rate
7/8 by construction, and the splice test says those accept at 0.51-0.60.
"""
import numpy as np
from scipy.special import logsumexp

# MBH sampling basis indices (settings sky_inds_map)
CI, PSI, LAM, SB = 6, 7, 8, 9
NG = 8


def orbit(x):
    """Return the 8 images of each row of ``x`` (N, ndim) under G."""
    out = []
    for k in range(4):
        for refl in (0, 1):
            y = np.asarray(x, dtype=np.float64).copy()
            if refl:
                y[:, SB] *= -1
                y[:, CI] *= -1
                y[:, PSI] = (np.pi - y[:, PSI]) % np.pi
            y[:, LAM] = (y[:, LAM] + k * np.pi / 2) % (2 * np.pi)
            y[:, PSI] = (y[:, PSI] + k * np.pi / 2) % np.pi
            out.append(y)
    return out


def _circd(a, b, per):
    d = np.abs(a - b) % per
    return np.minimum(d, per - d)


def fold_to_ref(x, ref):
    """Canonicalise each row to the orbit image nearest ``ref``.

    G-invariant (same orbit -> same representative). Used at TRAIN time only:
    it places the fundamental-domain cut away from the cloud, so a cloud that
    straddles a lam = k*pi/2 boundary is not torn in two (the group shifts lam
    and psi together, so a naive floor-based fold splits such clouds -- seen on
    leaf 0: K 1 -> 2).
    """
    ims = orbit(x)
    dist = np.stack([
        np.sqrt(_circd(im[:, LAM], ref[LAM], 2 * np.pi) ** 2
                + (im[:, SB] - ref[SB]) ** 2
                + _circd(im[:, PSI], ref[PSI], np.pi) ** 2
                + (im[:, CI] - ref[CI]) ** 2)
        for im in ims], 0)
    pick = np.argmin(dist, 0)
    return np.stack([ims[pick[i]][i] for i in range(len(x))], 0)


class FoldedFlow:
    """Wraps a flow trained on folded coords; proposes in the original basis.

    Exposes the ConditionalFlowMove contract (sample_and_log_prob / log_prob
    with a bare leaf context and optional base_scale), so it is a drop-in for
    the harness scorer. Needs no reference at proposal time -- the density is
    symmetrised over the whole orbit.
    """

    def __init__(self, flow, rng_seed=0):
        self.flow = flow
        self._rng = np.random.default_rng(rng_seed)

    def log_prob(self, x, context=None, base_scale=None):
        x = np.asarray(x, dtype=np.float64)
        big = np.concatenate(orbit(x), 0)                      # (8N, ndim)
        kw = {} if base_scale is None else dict(base_scale=base_scale)
        lp = self.flow.log_prob(big, context=context, **kw).reshape(NG, len(x))
        return logsumexp(lp, axis=0) - np.log(NG)

    def sample_and_log_prob(self, n, context=None, base_scale=None):
        kw = {} if base_scale is None else dict(base_scale=base_scale)
        u, _ = self.flow.sample_and_log_prob(int(n), context=context, **kw)
        ims = orbit(u)
        pick = self._rng.integers(0, NG, size=int(n))
        x = np.stack([ims[pick[i]][i] for i in range(int(n))], 0)
        return x, self.log_prob(x, context=context, base_scale=base_scale)
