# Auto-generated by lisatools — do not edit manually.
# Include this file in downstream CMakeLists.txt to get lisatools source lists.
#
# Usage:
#   include("${LISATOOLS_DIR}/cutils/lisatools_sources.cmake")
#   # Now available:
#   #   LISATOOLS_CU_SOURCES  — basenames of .cu files (Detector.cu, PSD.cu, ...)
#   #   LISATOOLS_HEADERS     — basenames of .hpp headers
#   #   lisatools_copy_cu_to_cxx()  — helper for CPU builds
#   #   lisatools_get_cu_paths()    — helper for GPU builds

set(LISATOOLS_CU_SOURCES
    Detector.cu;PSD.cu;domains.cu;galactic_response.cu
)

set(LISATOOLS_HEADERS
    Detector.hpp;PSD.hpp;domains.hpp;binding_detector.hpp;galactic_response.hpp
)

# Helper: generate copy commands for CPU builds (.cu → .cxx).
# Call after include(). Populates ${outvar} with the list of .cxx output paths.
#
#   lisatools_copy_cu_to_cxx(<lisatools_cutils_dir> <output_var>)
#
function(lisatools_copy_cu_to_cxx LISATOOLS_CUTILS_DIR OUTVAR)
    set(_cxx_outputs)
    foreach(_cu ${LISATOOLS_CU_SOURCES})
        string(REPLACE ".cu" ".cxx" _cxx "${_cu}")
        add_custom_command(
            OUTPUT "${_cxx}"
            COMMENT "Copy lisatools ${_cu} to ${_cxx}"
            COMMAND ${CMAKE_COMMAND} -E copy
                "${LISATOOLS_CUTILS_DIR}/${_cu}"
                "${CMAKE_CURRENT_BINARY_DIR}/${_cxx}"
            DEPENDS "${LISATOOLS_CUTILS_DIR}/${_cu}"
            VERBATIM
        )
        list(APPEND _cxx_outputs "${CMAKE_CURRENT_BINARY_DIR}/${_cxx}")
    endforeach()
    set(${OUTVAR} ${_cxx_outputs} PARENT_SCOPE)
endfunction()

# Helper: get full paths to .cu sources for GPU builds.
#
#   lisatools_get_cu_paths(<lisatools_cutils_dir> <output_var>)
#
function(lisatools_get_cu_paths LISATOOLS_CUTILS_DIR OUTVAR)
    set(_cu_paths)
    foreach(_cu ${LISATOOLS_CU_SOURCES})
        list(APPEND _cu_paths "${LISATOOLS_CUTILS_DIR}/${_cu}")
    endforeach()
    set(${OUTVAR} ${_cu_paths} PARENT_SCOPE)
endfunction()
